---------------------------------------
Begin Slurm Prolog: Feb-19-2025 01:36:46
Job ID:    1314473
User ID:   yzhang3942
Account:   coc
Job name:  evaluateGene
Partition: ice-gpu
QOS:       coe-ice
---------------------------------------
Launching AIsurBL
atl1-1-01-005-15-0.pace.gatech.edu
Lmod has detected the following error: The following module(s) are unknown:
"gcc/13.2.0"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "gcc/13.2.0"

Also make sure that all modulefiles written in TCL start with the string
#%Module




The following have been reloaded with a version change:
  1) cuda/12.6.1 => cuda/12.1.1

/var/lib/slurm/slurmd/job1314473/slurm_script: line 17: /opt/apps/Module/anaconda3/2021.11/bin/activate: No such file or directory
Traceback (most recent call last):
  File "/storage/ice1/0/2/yzhang3942/llm-guided-evolution/./sota/ultralytics/test.py", line 1, in <module>
    from ultralytics import YOLO
  File "/storage/ice1/0/2/yzhang3942/llm-guided-evolution/sota/ultralytics/ultralytics/__init__.py", line 11, in <module>
    from ultralytics.models import NAS, RTDETR, SAM, YOLO, FastSAM, YOLOWorld
  File "/storage/ice1/0/2/yzhang3942/llm-guided-evolution/sota/ultralytics/ultralytics/models/__init__.py", line 3, in <module>
    from .fastsam import FastSAM
  File "/storage/ice1/0/2/yzhang3942/llm-guided-evolution/sota/ultralytics/ultralytics/models/fastsam/__init__.py", line 3, in <module>
    from .model import FastSAM
  File "/storage/ice1/0/2/yzhang3942/llm-guided-evolution/sota/ultralytics/ultralytics/models/fastsam/model.py", line 5, in <module>
    from ultralytics.engine.model import Model
  File "/storage/ice1/0/2/yzhang3942/llm-guided-evolution/sota/ultralytics/ultralytics/engine/model.py", line 11, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "/storage/ice1/0/2/yzhang3942/llm-guided-evolution/sota/ultralytics/ultralytics/cfg/__init__.py", line 10, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
---------------------------------------
Begin Slurm Epilog: Feb-19-2025 01:36:55
Job ID:        1314473
User ID:       yzhang3942
Account:       coc
Job name:      evaluateGene
Resources:     cpu=4,gres/gpu:a100=2,mem=128G,node=1
Rsrc Used:     cput=00:00:36,vmem=0,walltime=00:00:09,mem=215572K,energy_used=0
Partition:     ice-gpu
QOS:           coe-ice
Nodes:         atl1-1-01-005-15-0
---------------------------------------
